- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS from play level"
    DURATION: "120HRS"
    TRAINER: "Sivakumar"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: COURSE
    prompt: enter course name
    private: false 
  - name: TRAINER
    prompt: Enter the trainer name
    private: false
  - name: DURATION
    prompt: enter the duration
    private: false
  tasks:
  - name: print the information
    vars:
      COURSE: "DevOps with AWS from task level"
      DURATION: "120HRS"
      TRAINER: "Sivakumar"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"


#1-args
#2-tasklevel
#3-files
#4-prompt
#5-play level
#6-inventory