- name: create user
  hosts: web
  become: yes #gives sudo access
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    regiser: USER #here USER is variable that stores output of above command
    ignore_errors: True #ignore the errors

  - name: print user information
    ansible.builtin.debug:
      msg: "user info: {{USER}}"