- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
  
  #ansible.builtin.shell--works for complex like pipes,redirectories
  #ansible.builtin.command--works for simple commands

  - name: check the process
    ansible.builtin.shell: ps -ef | grep ssh
    register: output